import { promises as fs } from "fs"
import path from "path"
import { copyDir, ensureDir, pathExists, readJson, readText, writeJson, writeText } from "../utils/files"
import { formatFrontmatter, parseFrontmatter } from "../utils/frontmatter"
import type { CodexAgent, CodexBundle } from "../types/codex"
import type { ClaudeHooks, ClaudeMcpServer } from "../types/claude"
import {
  pruneManagedOutput,
  removeLegacyBackupArtifacts,
  writeManagedOutputState,
} from "../utils/managed-output"
import { normalizeCodexName, transformContentForCodex } from "../utils/codex-content"

const STATE_FILE_NAME = ".compound-engineering-codex-state.json"
const CONFIG_BLOCK_START = "# BEGIN compound-plugin Codex MCP"
const CONFIG_BLOCK_END = "# END compound-plugin Codex MCP"
const LEGACY_MARKER = "# MCP servers synced from Claude Code"
const UNMARKED_LEGACY_MARKER = "# Generated by compound-plugin"

export async function writeCodexBundle(outputRoot: string, bundle: CodexBundle): Promise<void> {
  const paths = resolveCodexPaths(outputRoot, bundle.pluginName)
  await ensureDir(paths.codexRoot)

  const managedPaths = collectManagedPaths(paths, bundle)
  const normalizedManagedPaths = await pruneManagedOutput(paths.codexRoot, STATE_FILE_NAME, managedPaths)
  await removeLegacyBackupArtifacts(paths.codexRoot, [/^config\.toml\.bak\./])

  if (bundle.prompts.length > 0) {
    for (const prompt of bundle.prompts) {
      await writeText(path.join(paths.promptsRoot, `${safePathName(prompt.name)}.md`), prompt.content + "\n")
    }
  }

  for (const skill of bundle.skillDirs) {
    const targetDir = path.join(paths.skillsRoot, safePathName(skill.name))
    await copyDir(skill.sourceDir, targetDir)

    const raw = await readText(skill.skillPath ?? path.join(skill.sourceDir, "SKILL.md"))
    const parsed = parseFrontmatter(raw)
    const frontmatter: Record<string, unknown> = {
      name: normalizeCodexName(skill.name),
      description: skill.description ?? parsed.data.description,
    }
    if (skill.model) {
      frontmatter.model = skill.model
    }
    if (skill.disableModelInvocation) {
      frontmatter["disable-model-invocation"] = true
    }
    const body = transformContentForCodex(parsed.body.trim(), bundle.invocationTargets, {
      unknownSlashBehavior: "preserve",
    })
    await writeText(path.join(targetDir, "SKILL.md"), formatFrontmatter(frontmatter, body) + "\n")
  }

  for (const skill of bundle.generatedSkills) {
    const skillDir = path.join(paths.skillsRoot, safePathName(skill.name))
    await writeText(path.join(skillDir, "SKILL.md"), skill.content + "\n")
    for (const sidecar of skill.sidecarDirs ?? []) {
      await copyDir(sidecar.sourceDir, path.join(skillDir, sidecar.targetName))
    }
  }

  for (const agent of bundle.agents ?? []) {
    const agentName = safePathName(agent.name)
    await writeText(path.join(paths.agentsRoot, `${agentName}.toml`), renderCodexAgentToml(agent) + "\n")
    for (const sidecar of agent.sidecarDirs ?? []) {
      await copyDir(sidecar.sourceDir, path.join(paths.agentsRoot, agentName, sidecar.targetName))
    }
  }

  if (bundle.pluginName) {
    await writeCodexPluginPackage(paths, bundle)
    await writeCodexMarketplace(paths, bundle)
  }

  await mergeCodexConfigFile(paths.configPath, renderCodexConfig(bundle.mcpServers))
  if (bundle.pluginName) {
    await mergeCodexHooksFile(paths.hooksPath, bundle.hooks, bundle.pluginName)
  }

  await writeManagedOutputState(paths.codexRoot, STATE_FILE_NAME, normalizedManagedPaths)
}

type CodexPaths = {
  codexRoot: string
  agentsRoot: string
  promptsRoot: string
  configPath: string
  hooksPath: string
  homeRoot: string
  agentsHome: string
  skillsRoot: string
  marketplaceRoot: string
  marketplacePath: string
  pluginRoot?: string
  pluginSkillsRoot?: string
}

function resolveCodexPaths(outputRoot: string, pluginName?: string): CodexPaths {
  const codexRoot = resolveCodexRoot(outputRoot)
  const homeRoot = path.dirname(codexRoot)
  const agentsHome = path.join(homeRoot, ".agents")
  const safePluginName = pluginName ? safePathName(pluginName) : undefined
  const pluginRoot = safePluginName ? path.join(codexRoot, "plugins", safePluginName) : undefined

  return {
    codexRoot,
    agentsRoot: path.join(codexRoot, "agents"),
    promptsRoot: path.join(codexRoot, "prompts"),
    configPath: path.join(codexRoot, "config.toml"),
    hooksPath: path.join(codexRoot, "hooks.json"),
    homeRoot,
    agentsHome,
    skillsRoot: path.join(agentsHome, "skills"),
    marketplaceRoot: homeRoot,
    marketplacePath: path.join(agentsHome, "plugins", "marketplace.json"),
    pluginRoot,
    pluginSkillsRoot: pluginRoot ? path.join(pluginRoot, "skills") : undefined,
  }
}

function resolveCodexRoot(outputRoot: string): string {
  return path.basename(outputRoot) === ".codex" ? outputRoot : path.join(outputRoot, ".codex")
}

function collectManagedPaths(paths: CodexPaths, bundle: CodexBundle): string[] {
  const managed = new Set<string>()

  for (const prompt of bundle.prompts) {
    managed.add(path.join(paths.promptsRoot, `${safePathName(prompt.name)}.md`))
  }
  for (const skill of bundle.skillDirs) {
    managed.add(path.join(paths.skillsRoot, safePathName(skill.name)))
  }
  for (const skill of bundle.generatedSkills) {
    managed.add(path.join(paths.skillsRoot, safePathName(skill.name)))
  }
  for (const agent of bundle.agents ?? []) {
    const agentName = safePathName(agent.name)
    managed.add(path.join(paths.agentsRoot, `${agentName}.toml`))
    if ((agent.sidecarDirs ?? []).length > 0) {
      managed.add(path.join(paths.agentsRoot, agentName))
    }
  }
  if (bundle.mcpServers && Object.keys(bundle.mcpServers).length > 0) {
    managed.add(paths.configPath)
  }
  if (bundle.hooks && Object.keys(bundle.hooks.hooks).length > 0) {
    managed.add(paths.hooksPath)
  }
  if (paths.pluginRoot) {
    managed.add(paths.pluginRoot)
    managed.add(paths.marketplacePath)
  }

  return [...managed]
}

async function writeCodexPluginPackage(paths: CodexPaths, bundle: CodexBundle): Promise<void> {
  if (!paths.pluginRoot || !paths.pluginSkillsRoot || !bundle.pluginName) return

  await writeJson(path.join(paths.pluginRoot, ".codex-plugin", "plugin.json"), buildCodexPluginManifest(bundle))

  for (const skill of bundle.skillDirs) {
    const targetDir = path.join(paths.pluginSkillsRoot, safePathName(skill.name))
    await copyDir(path.join(paths.skillsRoot, safePathName(skill.name)), targetDir)
  }
  for (const skill of bundle.generatedSkills) {
    const targetDir = path.join(paths.pluginSkillsRoot, safePathName(skill.name))
    await copyDir(path.join(paths.skillsRoot, safePathName(skill.name)), targetDir)
  }
}

async function writeCodexMarketplace(paths: CodexPaths, bundle: CodexBundle): Promise<void> {
  if (!paths.pluginRoot || !bundle.pluginName) return

  const relativePluginPath = toMarketplacePath(paths.marketplaceRoot, paths.pluginRoot)
  await writeJson(paths.marketplacePath, {
    name: `${bundle.pluginName}-marketplace`,
    interface: {
      displayName: "Compound Engineering",
    },
    plugins: [
      {
        name: bundle.pluginName,
        source: {
          source: "local",
          path: relativePluginPath,
        },
        policy: {
          installation: "AVAILABLE",
          authentication: "ON_INSTALL",
        },
        category: "Coding",
      },
    ],
  })
}

function toMarketplacePath(marketplaceRoot: string, pluginRoot: string): string {
  const relativePath = path.relative(marketplaceRoot, pluginRoot).split(path.sep).join("/")
  if (relativePath === "") return "."
  if (relativePath.startsWith("../")) return relativePath
  return relativePath.startsWith("./") ? relativePath : `./${relativePath}`
}

function buildCodexPluginManifest(bundle: CodexBundle): Record<string, unknown> {
  return {
    name: bundle.pluginName,
    version: bundle.pluginVersion ?? "1.0.0",
    description: bundle.pluginDescription ?? "Compound Engineering Codex export generated by compound-plugin.",
    skills: "./skills/",
    interface: {
      displayName: "Compound Engineering",
      shortDescription: "Workflow, review, research, and engineering automation skills for Codex.",
      category: "Coding",
      capabilities: ["Read", "Write", "Interactive"],
    },
  }
}

async function mergeCodexConfigFile(configPath: string, mcpToml: string | null): Promise<void> {
  const existing = await readFileSafe(configPath)
  const merged = mergeCodexConfig(existing, mcpToml)
  if (merged === null || merged === existing) return
  await writeText(configPath, merged.endsWith("\n") ? merged : `${merged}\n`)
}

export function renderCodexConfig(mcpServers?: Record<string, ClaudeMcpServer>): string | null {
  if (!mcpServers || Object.keys(mcpServers).length === 0) return null

  const sections: string[] = []
  for (const [name, server] of Object.entries(mcpServers)) {
    if (!server.command && !server.url) continue

    const key = formatTomlKey(name)
    const lines: string[] = [`[mcp_servers.${key}]`]

    if (server.command) {
      lines.push(`command = ${formatTomlString(server.command)}`)
      if (server.args && server.args.length > 0) {
        const args = server.args.map((arg) => formatTomlString(arg)).join(", ")
        lines.push(`args = [${args}]`)
      }
      if (server.env && Object.keys(server.env).length > 0) {
        lines.push("")
        lines.push(`[mcp_servers.${key}.env]`)
        for (const [envKey, value] of Object.entries(server.env)) {
          lines.push(`${formatTomlKey(envKey)} = ${formatTomlString(value)}`)
        }
      }
    } else if (server.url) {
      lines.push(`url = ${formatTomlString(server.url)}`)
      if (server.headers && Object.keys(server.headers).length > 0) {
        lines.push(`http_headers = ${formatTomlInlineTable(server.headers)}`)
      }
    }

    sections.push(lines.join("\n"))
  }

  return sections.length > 0 ? sections.join("\n\n") + "\n" : null
}

export function mergeCodexConfig(existingContent: string, mcpToml: string | null): string | null {
  let stripped = removeManagedBlock(existingContent)

  if (!mcpToml) {
    if (!existingContent) return null
    const legacyMarkerIndex = stripped.indexOf(LEGACY_MARKER)
    if (legacyMarkerIndex !== -1) {
      return stripped.slice(0, legacyMarkerIndex).trimEnd()
    }
    return stripped === existingContent ? existingContent : stripped.trimEnd()
  }

  for (const marker of [LEGACY_MARKER, UNMARKED_LEGACY_MARKER]) {
    const markerIndex = stripped.indexOf(marker)
    if (markerIndex !== -1) {
      stripped = stripped.slice(0, markerIndex).trimEnd()
    }
  }

  const managedBlock = [CONFIG_BLOCK_START, mcpToml.trim(), CONFIG_BLOCK_END].join("\n")
  const prefix = stripped.trimEnd()
  return prefix ? `${prefix}\n\n${managedBlock}\n` : `${managedBlock}\n`
}

function removeManagedBlock(content: string): string {
  const start = content.indexOf(CONFIG_BLOCK_START)
  const end = content.indexOf(CONFIG_BLOCK_END)
  if (start === -1 || end === -1 || end < start) return content
  const before = content.slice(0, start).trimEnd()
  const after = content.slice(end + CONFIG_BLOCK_END.length).trimStart()
  return [before, after].filter(Boolean).join("\n\n")
}

async function mergeCodexHooksFile(
  hooksPath: string,
  hooks: ClaudeHooks | undefined,
  pluginName: string,
): Promise<void> {
  const pluginHooks = hooks?.hooks ?? {}
  const existing = await readJsonSafe(hooksPath)
  const merged = mergeCodexHooks(existing, pluginHooks, pluginName)
  const hasHooks = Object.keys((merged.hooks as Record<string, unknown>) ?? {}).length > 0
  const hasManaged = Object.keys((merged._managed as Record<string, unknown>) ?? {}).length > 0
  if (!hasHooks && !hasManaged) return
  await writeJson(hooksPath, merged)
}

type HookMatcher = {
  matcher?: string
  hooks: Array<{ type: string; command?: string; prompt?: string; agent?: string; timeout?: number }>
}

type ManagedHookIndex = Record<string, Record<string, number[]>>

export function mergeCodexHooks(
  existing: Record<string, unknown> | null,
  pluginHooks: Record<string, HookMatcher[]>,
  pluginName: string,
): Record<string, unknown> {
  const result: Record<string, unknown[]> = {}
  const existingHooks = (existing?.hooks ?? {}) as Record<string, unknown[]>
  const managed: ManagedHookIndex = ((existing?._managed as ManagedHookIndex | undefined) ?? {})
  const owned = managed[pluginName] ?? {}

  for (const [event, matchers] of Object.entries(existingHooks)) {
    if (!Array.isArray(matchers)) continue
    const ownedIndices = new Set(owned[event] ?? [])
    result[event] = matchers.filter((_matcher, index) => !ownedIndices.has(index))
  }

  const nextOwned: Record<string, number[]> = {}
  for (const [event, matchers] of Object.entries(pluginHooks)) {
    if (!result[event]) result[event] = []
    nextOwned[event] = []
    for (const matcher of matchers) {
      nextOwned[event].push(result[event].length)
      result[event].push(matcher)
    }
  }

  for (const event of Object.keys(result)) {
    if (result[event].length === 0) delete result[event]
  }

  if (Object.keys(nextOwned).length > 0) {
    managed[pluginName] = nextOwned
  } else {
    delete managed[pluginName]
  }

  const output: Record<string, unknown> = { hooks: result }
  if (Object.keys(managed).length > 0) {
    output._managed = managed
  }
  return output
}

function renderCodexAgentToml(agent: CodexAgent): string {
  const lines = [
    `name = ${formatTomlString(agent.name)}`,
    `description = ${formatTomlString(agent.description)}`,
    `developer_instructions = ${formatTomlString(agent.instructions)}`,
  ]
  if (agent.model) {
    lines.push(`model = ${formatTomlString(agent.model)}`)
  }
  return lines.join("\n")
}

function formatTomlString(value: string): string {
  return JSON.stringify(value)
}

function formatTomlKey(value: string): string {
  if (/^[A-Za-z0-9_-]+$/.test(value)) return value
  return JSON.stringify(value)
}

function formatTomlInlineTable(entries: Record<string, string>): string {
  const parts = Object.entries(entries).map(
    ([key, value]) => `${formatTomlKey(key)} = ${formatTomlString(value)}`,
  )
  return `{ ${parts.join(", ")} }`
}

function safePathName(value: string): string {
  return normalizeCodexName(value)
}

async function readFileSafe(filePath: string): Promise<string> {
  try {
    return await fs.readFile(filePath, "utf-8")
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err
    return ""
  }
}

async function readJsonSafe(filePath: string): Promise<Record<string, unknown> | null> {
  if (!(await pathExists(filePath))) return null
  try {
    return await readJson<Record<string, unknown>>(filePath)
  } catch {
    return null
  }
}
