#!/usr/bin/env bash
# Setup Ralph Loop
# Creates the state file that the stop hook reads to implement the loop.
#
# Usage: setup-ralph-loop.sh "<prompt>" --completion-promise "<text>" [--max-iterations <n>]

set -euo pipefail

STATE_DIR=".claude"
STATE_FILE="${STATE_DIR}/ralph-loop.local.md"

# Defaults
MAX_ITERATIONS=10
COMPLETION_PROMISE=""
PROMPT=""

# Parse arguments
while [ $# -gt 0 ]; do
  case "$1" in
    --max-iterations)
      MAX_ITERATIONS="$2"
      shift 2
      ;;
    --completion-promise)
      COMPLETION_PROMISE="$2"
      shift 2
      ;;
    *)
      if [ -z "$PROMPT" ]; then
        PROMPT="$1"
      else
        PROMPT="${PROMPT} $1"
      fi
      shift
      ;;
  esac
done

if [ -z "$PROMPT" ]; then
  echo "Error: No prompt provided." >&2
  echo "Usage: setup-ralph-loop.sh \"<prompt>\" --completion-promise \"<text>\" [--max-iterations <n>]" >&2
  exit 1
fi

if [ -z "$COMPLETION_PROMISE" ]; then
  echo "Error: --completion-promise is required." >&2
  exit 1
fi

# Create state directory if needed
mkdir -p "$STATE_DIR"

# Write state file
cat > "$STATE_FILE" <<EOF
---
active: true
iteration: 0
max_iterations: ${MAX_ITERATIONS}
completion_promise: ${COMPLETION_PROMISE}
original_prompt: ${PROMPT}
timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
---

# Ralph Loop State

This file tracks the current ralph loop iteration. It is automatically
created by the ralph-loop command and removed when the loop completes.

**Do not edit this file manually.**

- **Prompt:** ${PROMPT}
- **Max Iterations:** ${MAX_ITERATIONS}
- **Completion Promise:** ${COMPLETION_PROMISE}
EOF

echo "Ralph Loop configured:"
echo "  Prompt: ${PROMPT}"
echo "  Max iterations: ${MAX_ITERATIONS}"
echo "  Completion promise: ${COMPLETION_PROMISE}"
echo ""
echo "The loop will run until Claude outputs <promise>${COMPLETION_PROMISE}</promise>"
echo "or ${MAX_ITERATIONS} iterations are reached."
